Implement registration and login
aitmamatovmusa/json pull request #4
Opened 2024-07-14 19:19 UTC by aitmamatovmusa

## Changes:
- Connect express session to generate a session token
- Set up redis to cache some data
- Create endpoints for login and registration

2024-07-15 16:21 UTC, Alex-2kZharkov requested changes

2024-07-15 16:21 UTC, Alex-2kZharkov commented on package.json
> +    "bcrypt": "^5.1.1",
node js have native module for such things, please, check and use it

2024-07-15 16:21 UTC, Alex-2kZharkov commented on package.json
> +    "@types/bcrypt": "^5.0.2",
same

2024-07-15 16:21 UTC, Alex-2kZharkov commented on src/@types/cacheManagerRedisStore.d.ts
> +declare module 'cache-manager-redis-store' {
this module is for short access, right?

2024-07-15 16:21 UTC, Alex-2kZharkov commented on src/app.module.ts
> +  async configure(consumer: MiddlewareConsumer) {
I am not sure you need to do this in the AppModule. Could you please show some docs or guide that you've followed?

2024-07-15 16:21 UTC, Alex-2kZharkov commented on src/auth/auth.controller.ts
> +@Controller()
it should be `api/v1/auth/login`. Add `auth` prefix here

2024-07-15 16:21 UTC, Alex-2kZharkov commented on src/auth/auth.controller.ts
> +@Controller()
the `v1` - is the homework, check out how NestJS advises this to do

2024-07-15 16:21 UTC, Alex-2kZharkov commented on src/auth/auth.controller.ts
> +  login(@Req() req, @Res() res) {
set the return type for this function

2024-07-15 16:21 UTC, Alex-2kZharkov commented on src/auth/auth.controller.ts
> +  register(@Body() registerData: RegisterDto) {
set the return type for this function

2024-07-15 16:21 UTC, Alex-2kZharkov commented on src/auth/auth.controller.ts
> +import { RegisterDto } from './dto/register.dto';
better to located this `dto` in the same folder

2024-07-15 16:21 UTC, Alex-2kZharkov commented on src/auth/auth.module.ts
> +export class AuthModule {}
this module should also be in the `features` folder. It is also a feature

2024-07-15 16:21 UTC, Alex-2kZharkov commented on src/features/accounts/account.entity.ts
> +  created_at: Date;
no-no, only camelCase. It is okay even for a database

2024-07-15 16:21 UTC, Alex-2kZharkov commented on src/features/accounts/account.entity.ts
> +  updated_at: Date;
same

2024-07-15 16:21 UTC, Alex-2kZharkov commented on src/features/accounts/account.entity.ts
> +  password: string;
create a task for yourself: how do you store password secure in a database?

2024-07-15 16:21 UTC, Alex-2kZharkov commented on src/features/accounts/accounts.service.ts
> +    const { fullname, email, password } = accountData;
do it on  the line 21

2024-07-15 16:21 UTC, Alex-2kZharkov commented on src/features/accounts/accounts.service.ts
> +    const { fullname, email, password } = accountData;
https://github.com/airbnb/javascript?tab=readme-ov-file#destructuring

2024-07-15 16:21 UTC, Alex-2kZharkov commented on src/features/accounts/accounts.service.ts
> +    const saltOrRounds = 10;
create a separate service for this like a PasswordService. You are violating Single Responsibility principle

2024-07-15 16:21 UTC, Alex-2kZharkov commented on src/features/accounts/accounts.service.ts
> +    const saltOrRounds = 10;
from Solid

2024-07-15 16:21 UTC, Alex-2kZharkov commented on src/redis/redis.module.ts
> +import * as redisStore from 'cache-manager-redis-store';
I would put this module in the `database` folder

2024-07-15 16:21 UTC, Alex-2kZharkov commented on src/redis/redis.module.ts
> +import * as redisStore from 'cache-manager-redis-store';
it belongs there. I have never seen a `redis` folder in the `src` folder

2024-07-15 16:21 UTC, Alex-2kZharkov commented on src/features/accounts/accounts.service.ts
> +    const saltOrRounds = 10;
make this a private readonly field

2024-07-15 16:21 UTC, Alex-2kZharkov commented on src/features/accounts/accounts.service.ts
> +    const account = await this.accountsRepository.create({
can you combine the `.create()` and the `.save()` methods?

2024-07-20 08:07 UTC, aitmamatovmusa commented
Todo
- Review Open closed principle
- Finish Authors, Posts, Quota

2024-07-31 05:52 UTC, Alex-2kZharkov commented on .env.example
Good! Keep it that way, it is a good practice

2024-07-31 06:11 UTC, Alex-2kZharkov requested changes

2024-07-31 06:11 UTC, Alex-2kZharkov commented on package.json
> +    "@nestjs/cache-manager": "^2.2.2",
I want you to get familiar with "^". People rare pay attention to it.
I want:
1) read this [article](https://stackoverflow.com/a/22345808) 
2) move all packages to a version without a "^"

2024-07-31 06:11 UTC, Alex-2kZharkov commented on src/app.controller.spec.ts
just remove the file

2024-07-31 06:11 UTC, Alex-2kZharkov commented on src/app.controller.ts
same. remove the file if we don't need it anymore

2024-07-31 06:11 UTC, Alex-2kZharkov commented on src/app.module.ts
> +import { AppConfigModule } from './database/appConfig/appConfig.module';
create an `index.ts` file and reexport `appConfig.module` from via index.ts, so it becomes ---> `import { AppConfigModule } from './database/appConfig`. Otherwise, it is looks ugly + you showed implementation which is wrong

2024-07-31 06:11 UTC, Alex-2kZharkov commented on src/common/filters/http.filter.ts
Good! Now you are familiar with Exceptions

2024-07-31 06:11 UTC, Alex-2kZharkov commented on src/common/interceptors/response.interceptor.ts
Good!

2024-07-31 06:11 UTC, Alex-2kZharkov commented on src/database/appConfig/appConfig.entity.ts
> +export class AppConfig extends BaseEntity {
rename it to just `Config`. It is obvious that we talk about general configs in the app. There is no need to mention it explicitly

2024-07-31 06:11 UTC, Alex-2kZharkov commented on src/database/appConfig/appConfig.module.ts
rename all related parts to `config`

2024-07-31 06:11 UTC, Alex-2kZharkov commented on src/database/migrations/1721756269144-baseEntity.ts
excellent, your first migration! I am glad we you did it

2024-07-31 06:11 UTC, Alex-2kZharkov commented on src/database/migrations/1722176088433-appConfig.ts
> +        await queryRunner.query(`CREATE TABLE "app_config" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
this one is needed to be updated after changing name of the table

2024-07-31 06:11 UTC, Alex-2kZharkov commented on src/features/accounts/accounts.controller.ts
> +export class AccountsController {}
why is this controller empty?

2024-07-31 06:11 UTC, Alex-2kZharkov commented on src/features/accounts/accounts.service.ts
> +  async validateUser(): Promise<boolean> {
this one looks strange. Maybe you need to remove it?

2024-07-31 06:11 UTC, Alex-2kZharkov commented on src/features/accounts/password.service.ts
> +  async comparePasswords({ storedHash, password }): Promise<boolean> {
change the place of `comparePasswords` and `hashPassword` functions. It is better when you call the `hashPassword`, and it is located right under the function `comparePasswords`

2024-07-31 06:11 UTC, Alex-2kZharkov commented on src/features/auth/auth.controller.ts
> +  @HttpCode(HttpStatus.OK)
good points, 200 is more appropriate

2024-07-31 06:11 UTC, Alex-2kZharkov commented on src/features/auth/auth.service.ts
> +    const match = await this.passwordService.comparePasswords({
match ---> isPasswordValid

2024-07-31 06:11 UTC, Alex-2kZharkov commented on src/features/auth/auth.service.ts
> +    session.save();
do you need `await session.save()`??

2024-07-31 06:11 UTC, Alex-2kZharkov commented on src/features/auth/types.ts
> +export { LoginResponse };
do this one line 1

2024-07-31 07:57 UTC, aitmamatovmusa commented on package.json
> +    "@nestjs/cache-manager": "^2.2.2",
Gotcha! Moving all packages to the exact versions? Not even to minor versions `~`?
Like that?
```
"@nestjs/cache-manager": "2.2.2",
```

2024-07-31 09:12 UTC, aitmamatovmusa commented on src/features/accounts/accounts.controller.ts
> +export class AccountsController {}
because it does nothing currently

2024-07-31 11:38 UTC, Alex-2kZharkov commented on package.json
> +    "@nestjs/cache-manager": "^2.2.2",
exactly

2024-08-03 07:20 UTC, Alex-2kZharkov approved these changes

2024-08-03 07:22 UTC, merged